# reader name
reader_name = "My Reader"

# speedway _address
speedway_address = "192.168.55.12"

# socket server port for listening
# default: 11000
socket_port = 11000

# default: 0
session = 1

# default: 20
tag_population = 30

# possible values: "MaxThroughput=0", "Hybrid=1", "DenseReaderM4=2", "DenseReaderM8=3",
# "MaxMiller=4", "DenseReaderM4Two=5", "AutoSetDenseReader=1000", "AutoSetDenseReaderDeepScan=1002",
# "AutoSetStaticFast=1003", "AutoSetStaticDRM=1004", "AutoSetCustom or Impinj Internal = 1005"
rf_mode = 2

# possible values: "DualTarget", "SingleTarget", "ReaderSelected",
# "TagFocus", "SingleTargetReset", "DualTargetBtoASelect"
# default: "DualTarget"
selected_search_mode = "DualTarget"

# config to enable filter
[filter]
enabled = false
tag_mask = "0000"
bit_count = 16

[[antennas]]
ant_id = 1
tx_power = 17.0
rx_sensitivity = -60.0
enable = true

[[antennas]]
ant_id = 2
tx_power = 30.0
rx_sensitivity = -70.0
enable = true

[[antennas]]
ant_id = 3
tx_power = 30.0
rx_sensitivity = -70.0
enable = true

[[antennas]]
ant_id = 4
tx_power = 30.0
rx_sensitivity = -70.0
enable = true
