# speed way address
socket_address="localhost"

# socket port
socket_port=11000

# tx power
tx_power = 17

# sensitivity index
receiver_sensitivity_index = 2
# sensitivity specific antenna
# receiver_sensitivity = {1 = 1, 2 = 42}

# mqtt broker address
mqtt_broker_address = "192.168.55.148"

# mqtt port
# mqtt_port = 1883

# mqtt user
mqtt_user = "dev"

# mqtt password
mqtt_passwd = "laoitdev"

# shutdown timeout in seconds
# sihutdown_timeout = 20

# clean expire tag interval in seconds
cleanup_interval = 2

# report tag
report_every_n_tags = 1

# search mode
search_mode = 2 # 1 = single target, 2 = dual target

# tag timeout
tag_timeout = 3

# tag population config
tag_population = 32

# event id
event_id = 10003

[[gates]]
# gate id
gate_id="10001"
# supported ant
ant = [1, 2]
# ipcame gateway
ipcame_gateway_address="localhost"
# ipcame gateway port
ipcame_port=5555
# camera id
camera_id=0

[[gates]]
# gate id
gate_id="10002"
# supported ant
ant = [3, 4]
# ipcame gateway
ipcame_gateway_address="localhost"
# ipcame gateway port
ipcame_port=5555
# camera id
camera_id=1
