# service API port
SERVICE_PORT= 5555

#directories save image
SAVE_CAMERA_IMAGE_DIR_NAME="images"

# # set image size
image_width=1280
image_height=780

# # specify rorate camera image
rotate="ROTATE_180" # posible value ROTATE_90_CLOCKWISE, ROTATE_180, ROTATE_90_COUNTERCLOCKWISE

# list of ip camera config

[[ipcame]]
# ip camera address
IP_CAMERA_ADDRESS="192.168.55.66"
# rtsp port
RTSP_PORT=554
# ip came user
IP_CAMERA_USER="admin"
#ip came password
IP_CAMERA_PASSWORD="laoitdeV"
# camera channel
IP_CAMERA_CHANNEL=101 # main-stream=101, sub-stream=102
# relation gate id
relate_gate_id = 10001


[[ipcame]]
# ip camera address
IP_CAMERA_ADDRESS="192.168.55.65"
# rtsp port
RTSP_PORT=554
# ip came user
IP_CAMERA_USER="admin"
#ip came password
IP_CAMERA_PASSWORD="laoitdeV"
# camera channel
IP_CAMERA_CHANNEL=101 # main-stream=101, sub-stream=102
# relation gate id
relate_gate_id = 10002

